
import React from 'react';
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Share, Download, Flame } from "lucide-react";

interface RoastCardProps {
  roastText: string;
  style: string;
  onShare: () => void;
  onDownload: () => void;
}

const RoastCard: React.FC<RoastCardProps> = ({ roastText, style, onShare, onDownload }) => {
  return (
    <div className="space-y-4">
      <h3 className="text-xl font-bold text-center text-orange-400">Your Roast Meme Card 🔥</h3>
      
      {/* Meme Card */}
      <Card className="bg-gradient-to-br from-black via-gray-900 to-black border-2 border-orange-500 p-6 max-w-md mx-auto">
        <div className="text-center space-y-4">
          {/* Header */}
          <div className="bg-gradient-to-r from-orange-500 to-pink-500 text-white py-2 px-4 rounded-full">
            <div className="flex items-center justify-center">
              <Flame className="w-5 h-5 mr-2 animate-pulse" />
              <span className="font-bold">AI ROASTED</span>
              <Flame className="w-5 h-5 ml-2 animate-pulse" />
            </div>
          </div>

          {/* Profile placeholder */}
          <div className="w-24 h-24 bg-gradient-to-br from-pink-500 to-orange-500 rounded-full mx-auto flex items-center justify-center">
            <span className="text-3xl">😅</span>
          </div>

          {/* Roast Text */}
          <div className="bg-black/50 border border-orange-500/30 rounded-lg p-4">
            <p className="text-white font-bold text-lg leading-relaxed">
              "{roastText}"
            </p>
          </div>

          {/* Footer */}
          <div className="text-xs text-gray-400 space-y-1">
            <p>🔥 Generated by AI Profile Roaster 🔥</p>
            <p>For entertainment only - All in good fun! 😂</p>
          </div>

          {/* Watermark */}
          <div className="text-xs text-orange-400 font-bold">
            AIProfileRoaster.com
          </div>
        </div>
      </Card>

      {/* Action Buttons */}
      <div className="flex gap-3 justify-center">
        <Button 
          onClick={onShare}
          className="bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white"
        >
          <Share className="w-4 h-4 mr-2" />
          Share on WhatsApp
        </Button>
        <Button 
          onClick={onDownload}
          className="bg-gradient-to-r from-green-500 to-teal-500 hover:from-green-600 hover:to-teal-600 text-white"
        >
          <Download className="w-4 h-4 mr-2" />
          Download Image
        </Button>
      </div>
    </div>
  );
};

export default RoastCard;
